import Layout from '../components/layout/Layout'
import "../../node_modules/bootstrap/dist/css/bootstrap.min.css";
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import AuthProvider from '@/components/AuthProvider';
import { getServerSession } from "next-auth/next"
import { options } from './api/auth/[...nextauth]/options';
import { UserInfo } from '@/models/types';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Shopping Cart',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const session = await getServerSession(options)
  let userInfo = undefined
  if (session) userInfo = session.user as UserInfo
  console.log(userInfo)

  return (
    <html lang="en">
      <body className={inter.className} suppressHydrationWarning={true}>
        <AuthProvider>  
          <Layout userInfo={userInfo}>
            {children}
          </Layout>
        </AuthProvider>
      </body>
    </html>
  )
}
