import Layout from '../components/layout/Layout'
import "../../node_modules/bootstrap/dist/css/bootstrap.min.css";
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import AuthProvider from '@/components/AuthProvider';
import { getServerSession } from "next-auth/next"
import { options } from './api/auth/[...nextauth]/options';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Shopping Cart',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const session = await getServerSession(options)
  let isSignin

  if (!session) {
      console.log("not sign in" + session)
  } else {
    console.log(session)
  }

  return (
    <html lang="en">
      <body className={inter.className} suppressHydrationWarning={true}>
        <AuthProvider>  
          <Layout>
            {children}
          </Layout>
        </AuthProvider>
      </body>
    </html>
  )
}
